name: pa11y
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build --if-present
      - run: |
            npm run pa11y-ci app/assets/snapshots/capabilityLeads-snapshot.html, {ignore: ['WCAG2AA.Principle3.Guideline3_1.3_1_1.H93']}
            npm run pa11y-ci app/assets/snapshots/competencies-snapshot.html
            npm run pa11y-ci app/assets/snapshots/createCapabilty-snapshot.html
            npm run pa11y-ci app/assets/snapshots/jobFamilies-snapshot.html
            npm run pa11y-ci app/assets/snapshots/jobRoles-snapshot.html
            npm run pa11y-ci app/assets/snapshots/jobSpec-snapshot.html
            npm run pa11y-ci app/assets/snapshots/home-snapshot.html
            npm run pa11y-ci app/assets/snapshots/viewCapabilityLeads-snapshot.html
